/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ActionButtonProps {
  text: string;
}

const ActionButton: React.FC<ActionButtonProps> = ({ text }) => {
  return (
    <button className="overflow-hidden gap-2.5 self-stretch px-12 py-3 my-auto text-lg font-semibold text-center text-white bg-teal-500 rounded-2xl shadow-[0px_4px_24px_rgba(0,0,0,0.2)] max-md:px-5">
      {text}
    </button>
  );
};

export default ActionButton;
