/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TestimonialCard from "./TestimonialCard";
import ActionButton from "./ActionButton";
import NavigationButton from "./NavigationButton";

interface CustomerTestimonialsProps {
  testimonials: Array<{
    name: string;
    rating: number;
    content: string;
    imageSrc: string;
    usefulCount: number;
    daysAgo: number;
  }>;
}

const CustomerTestimonials: React.FC<CustomerTestimonialsProps> = ({
  testimonials,
}) => {
  return (
    <section className="flex flex-wrap gap-6 justify-between items-center">
      <div className="flex flex-col self-stretch my-auto min-w-[240px] w-[424px] max-md:max-w-full">
        <div className="flex flex-col w-full text-gray-600 max-md:max-w-full">
          <h2 className="text-3xl font-semibold max-md:max-w-full">
            What Our customers say about us
          </h2>
          <p className="mt-4 text-base font-medium max-md:max-w-full">
            Pellentesque etiam blandit in tincidunt at donec. Eget ipsum
            dignissim placerat nisi, adipiscing mauris non purus parturient.
          </p>
        </div>
        <div className="flex gap-8 justify-center items-center self-start mt-10">
          <ActionButton text="View All" />
          <NavigationButton direction="left" />
          <NavigationButton direction="right" />
        </div>
      </div>
      <div className="flex flex-col self-stretch my-auto rounded-lg min-w-[240px] w-[871px] max-md:max-w-full">
        {testimonials.map((testimonial, index) => (
          <TestimonialCard key={index} {...testimonial} />
        ))}
      </div>
    </section>
  );
};

export default CustomerTestimonials;
