/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface NavigationButtonProps {
  direction: "left" | "right";
}

const NavigationButton: React.FC<NavigationButtonProps> = ({ direction }) => {
  const rotation = direction === "left" ? "rotate-[3.141592653589793rad]" : "";
  const imageSrc = direction === "left" ? "/left.svg" : "/right.svg";

  return (
    <button
      className={`flex overflow-hidden gap-2.5 justify-center items-center self-stretch px-2 my-auto w-12 h-12 bg-white rounded-lg ${rotation} shadow-[0px_4px_24px_rgba(0,0,0,0.08)]`}
    >
      <img
        loading="lazy"
        src={imageSrc}
        alt={`Navigate ${direction}`}
        className="object-contain self-stretch my-auto w-8 aspect-square"
      />
    </button>
  );
};

export default NavigationButton;
